//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gantt_rest_net.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class announcement
    {
        public short ID { get; set; }
        public System.DateTime date { get; set; }
        public short supervisorID { get; set; }
        public string mesage { get; set; }
        public Nullable<short> versionID { get; set; }
    
        public virtual supervisor supervisor { get; set; }
        public virtual version version { get; set; }
    }
}
