//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gantt_rest_net.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        public short projectID { get; set; }
        public string projectName { get; set; }
        public short groupID { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
