//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gantt_rest_net.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public short reportID { get; set; }
        public System.DateTime date { get; set; }
        public string reportName { get; set; }
        public short projectID { get; set; }
        public string text { get; set; }
        public Nullable<short> updatedBy { get; set; }
    
        public virtual student student { get; set; }
    }
}
