//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gantt_rest_net.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.groups = new HashSet<groups>();
            this.groups1 = new HashSet<groups>();
            this.groups2 = new HashSet<groups>();
            this.groups3 = new HashSet<groups>();
            this.groups4 = new HashSet<groups>();
            this.report = new HashSet<report>();
        }
    
        public short studentID { get; set; }
        public string studentName { get; set; }
        public string studentSurname { get; set; }
        public string studentEmail { get; set; }
        public string studentPassword { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
        public virtual ICollection<groups> groups1 { get; set; }
        public virtual ICollection<groups> groups2 { get; set; }
        public virtual ICollection<groups> groups3 { get; set; }
        public virtual ICollection<groups> groups4 { get; set; }
        public virtual ICollection<report> report { get; set; }
    }
}
